{
    'targets': [{
        'target_name': 'libwebp',
        'type': 'static_library',
        'include_dirs': [
            '../third-party/libwebp/src/',
            '../third-party/libwebp/src/webp/',
            '../third-party/libwebp/src/dsp/',
        ],
        'direct_dependent_settings': {
            'include_dirs': [
                '../third-party/libwebp/src/',
                '../third-party/libwebp/src/webp/',
                '../third-party/libwebp/src/dsp/',
            ],
        },
        'cflags': [
            '-fvisibility=hidden',
            '-Wall',
            '-Wconstant-conversion',
            '-Wdeclaration-after-statement',
            '-Wextra',
            '-Wfloat-conversion',
            '-Wformat -Wformat-nonliteral',
            '-Wformat -Wformat-security',
            '-Wmissing-declarations',
            '-Wmissing-prototypes',
            '-Wold-style-definition',
            '-Wparentheses-equality',
            '-Wshadow',
            '-Wshorten-64-to-32',
            '-Wunreachable-code',
            '-Wunused-but-set-variable',
            '-Wunused',
            '-Wvla'
        ],
        'libraries': [
            '-lm'
        ],
        'sources': [
            '../third-party/libwebp/src/utils/bit_reader_utils.c',
            '../third-party/libwebp/src/utils/bit_reader_utils.h',
            '../third-party/libwebp/src/utils/bit_reader_inl_utils.h',
            '../third-party/libwebp/src/utils/color_cache_utils.c',
            '../third-party/libwebp/src/utils/color_cache_utils.h',
            '../third-party/libwebp/src/utils/endian_inl_utils.h',
            '../third-party/libwebp/src/utils/filters_utils.c',
            '../third-party/libwebp/src/utils/filters_utils.h',
            '../third-party/libwebp/src/utils/huffman_utils.c',
            '../third-party/libwebp/src/utils/huffman_utils.h',
            '../third-party/libwebp/src/utils/quant_levels_dec_utils.c',
            '../third-party/libwebp/src/utils/quant_levels_dec_utils.h',
            '../third-party/libwebp/src/utils/rescaler_utils.c',
            '../third-party/libwebp/src/utils/rescaler_utils.h',
            '../third-party/libwebp/src/utils/random_utils.c',
            '../third-party/libwebp/src/utils/random_utils.h',
            '../third-party/libwebp/src/utils/thread_utils.c',
            '../third-party/libwebp/src/utils/thread_utils.h',
            '../third-party/libwebp/src/utils/utils.c',
            '../third-party/libwebp/src/utils/utils.h',
            '../third-party/libwebp/src/dsp/alpha_processing.c',
            '../third-party/libwebp/src/dsp/alpha_processing_mips_dsp_r2.c',
            '../third-party/libwebp/src/dsp/common_sse2.h',
            '../third-party/libwebp/src/dsp/cost.c',
            '../third-party/libwebp/src/dsp/cpu.c',
            '../third-party/libwebp/src/dsp/dec.c',
            '../third-party/libwebp/src/dsp/dec_clip_tables.c',
            '../third-party/libwebp/src/dsp/dec_mips32.c',
            '../third-party/libwebp/src/dsp/dec_mips_dsp_r2.c',
            '../third-party/libwebp/src/dsp/dsp.h',
            '../third-party/libwebp/src/dsp/enc.c',
            '../third-party/libwebp/src/dsp/filters.c',
            '../third-party/libwebp/src/dsp/filters_mips_dsp_r2.c',
            '../third-party/libwebp/src/dsp/lossless.c',
            '../third-party/libwebp/src/dsp/lossless.h',
            '../third-party/libwebp/src/dsp/lossless_common.h',
            '../third-party/libwebp/src/dsp/lossless_enc.c',
            '../third-party/libwebp/src/dsp/lossless_enc_sse2.c',
            '../third-party/libwebp/src/dsp/lossless_mips_dsp_r2.c',
            '../third-party/libwebp/src/dsp/mips_macro.h',
            '../third-party/libwebp/src/dsp/rescaler.c',
            '../third-party/libwebp/src/dsp/rescaler_mips32.c',
            '../third-party/libwebp/src/dsp/rescaler_mips_dsp_r2.c',
            '../third-party/libwebp/src/dsp/upsampling.c',
            '../third-party/libwebp/src/dsp/upsampling_mips_dsp_r2.c',
            '../third-party/libwebp/src/dsp/yuv.c',
            '../third-party/libwebp/src/dsp/yuv.h',
            '../third-party/libwebp/src/dsp/yuv_mips32.c',
            '../third-party/libwebp/src/dsp/yuv_mips_dsp_r2.c',
            '../third-party/libwebp/src/enc/alpha_enc.c',
            '../third-party/libwebp/src/enc/analysis_enc.c',
            '../third-party/libwebp/src/enc/backward_references_enc.c',
            '../third-party/libwebp/src/enc/backward_references_enc.h',
            '../third-party/libwebp/src/enc/config_enc.c',
            '../third-party/libwebp/src/enc/cost_enc.c',
            '../third-party/libwebp/src/enc/cost_enc.h',
            '../third-party/libwebp/src/enc/delta_palettization_enc.c',
            '../third-party/libwebp/src/enc/delta_palettization_enc.h',
            '../third-party/libwebp/src/enc/filter_enc.c',
            '../third-party/libwebp/src/enc/frame_enc.c',
            '../third-party/libwebp/src/enc/histogram_enc.c',
            '../third-party/libwebp/src/enc/histogram_enc.h',
            '../third-party/libwebp/src/enc/iterator_enc.c',
            '../third-party/libwebp/src/enc/near_lossless_enc.c',
            '../third-party/libwebp/src/enc/picture_enc.c',
            '../third-party/libwebp/src/enc/picture_csp_enc.c',
            '../third-party/libwebp/src/enc/picture_psnr_enc.c',
            '../third-party/libwebp/src/enc/picture_rescale_enc.c',
            '../third-party/libwebp/src/enc/picture_tools_enc.c',
            '../third-party/libwebp/src/enc/predictor_enc.c',
            '../third-party/libwebp/src/enc/quant_enc.c',
            '../third-party/libwebp/src/enc/syntax_enc.c',
            '../third-party/libwebp/src/enc/token_enc.c',
            '../third-party/libwebp/src/enc/tree_enc.c',
            '../third-party/libwebp/src/enc/vp8i_enc.h',
            '../third-party/libwebp/src/enc/vp8l_enc.c',
            '../third-party/libwebp/src/enc/vp8li_enc.h',
            '../third-party/libwebp/src/enc/webp_enc.c',
            '../third-party/libwebp/src/dec/alpha_dec.c',
            '../third-party/libwebp/src/dec/alphai_dec.h',
            '../third-party/libwebp/src/dec/buffer_dec.c',
            '../third-party/libwebp/src/dec/common_dec.h',
            '../third-party/libwebp/src/dec/vp8_dec.h',
            '../third-party/libwebp/src/dec/frame_dec.c',
            '../third-party/libwebp/src/dec/idec_dec.c',
            '../third-party/libwebp/src/dec/io_dec.c',
            '../third-party/libwebp/src/dec/quant_dec.c',
            '../third-party/libwebp/src/dec/tree_dec.c',
            '../third-party/libwebp/src/dec/vp8_dec.c',
            '../third-party/libwebp/src/dec/vp8i_dec.h',
            '../third-party/libwebp/src/dec/vp8l_dec.c',
            '../third-party/libwebp/src/dec/vp8li_dec.h',
            '../third-party/libwebp/src/dec/webp_dec.c',
            '../third-party/libwebp/src/dec/webpi_dec.h',
            '../third-party/libwebp/src/webp/encode.h',
            '../third-party/libwebp/src/webp/decode.h',
            '../third-party/libwebp/src/webp/types.h',
            '../third-party/libwebp/src/webp/format_constants.h',
        ],
    }],
    'configurations': {
        'Debug': {
            'cflags': [ '-g', '-O0' ],
            'xcode_settings': {
                'OTHER_CFLAGS': [ '-g', '-O0' ]
            }
        },
        'Release': {
            'cflags': [ '-g', '-O3' ],
            'defines': [ 'NDEBUG' ],
            'xcode_settings': {
                'OTHER_CFLAGS': [ '-g', '-O3' ]
            }
        }
    },
}
